// AUTO GENERATOR
const Major = [];
const major = [
    "CAUnotice",
    "adpr",
    "ai",
    "appliedStat",
    "architecture",
    "business",
    "chem",
    "chemEngineering",
    "chinese",
    "civilEnvPlanEng",
    "davinci",
    "dorm",
    "earlyChildhoodEd",
    "econ",
    "education",
    "elecEngineering",
    "enerEngineering",
    "english",
    "englishEd",
    "french",
    "german",
    "history",
    "industSec",
    "integEngineering",
    "japanese",
    "korean",
    "libInfoScience",
    "lifeScience",
    "logistics",
    "math",
    "mechEngineering",
    "med",
    "mediaComm",
    "nursing",
    "pharm",
    "philosophy",
    "physicalEd",
    "physics",
    "polaris",
    "politics",
    "psychology",
    "publicService",
    "russian",
    "socialWelfare",
    "sociology",
    "software",
    "upreJob",
    "urbanEngineering",
    "urbanPlanRealEstate"
];
const len = major.length;
for(let i=0;i<len;i++){
    Major[i] = major[i].charAt(0).toUpperCase() + major[i].slice(1);
}

// ${major[i]}

for(let i=0;i<len;i++){
    console.log(``);
}

// const major = [
    // "CAUnotice",
    // "adpr",
    // "ai",
    // "appliedStat",
    // "architecture",
    // "business",
    // "chem",
    // "chemEngineering",
    // "chinese",
    // "civilEnvPlanEng",
    // "davinci",
    // "dorm",
    // "earlyChildhoodEd",
    // "econ",
    // "education",
    // "elecEngineering",
    // "enerEngineering",
    // "english",
    // "englishEd",
    // "french",
    // "german",
    // "history",
    // "industSec",
    // "integEngineering",
    // "japanese",
    // "korean",
    // "libInfoScience",
    // "lifeScience",
    // "logistics",
    // "math",
    // "mechEngineering",
    // "med",
    // "mediaComm",
    // "nursing",
    // "pharm",
    // "philosophy",
    // "physicalEd",
    // "physics",
    // "polaris",
    // "politics",
    // "psychology",
    // "publicService",
    // "russian",
    // "socialWelfare",
    // "sociology",
    // "software",
    // "upreJob",
    // "urbanEngineering",
    // "urbanPlanRealEstate"
// ];