const KRname = function func(input){
    if(input == "industSec")            return "산업보안학과";
    if(input == "software") return "소프트웨어학부";
    if(input == "CAUnotice") return "CAU Notice";
    if(input == "integEngineering") return "융합공학부";
    if(input == "korean") return "국어국문학과";
    if(input == "mechEngineering") return "기계공학부";
    if(input == "psychology") return "심리학과";
    if(input == "business") return "경영학부";
    if(input == "elecEngineering") return "전기전자공학부";
    if(input == "english") return "영어영문학과";
    if(input == "enerEngineering") return "에너지시스템공학부";
    if(input == "urbanPlanRealEstate") return "도시계획부동산학과";
    if(input == "nursing") return "간호학과";
    if(input == "politics") return "정치국제학과";
    if(input == "physicalEd") return "체육교육과";
    if(input == "education") return "교육학과";
    if(input == "earlyChildhoodEd") return "유아교육학과";
    if(input == "englishEd") return "영어교육과";
    if(input == "chem") return "화학과";
    if(input == "lifeScience") return "생명과학과";
    if(input == "japanese") return "일본어문학전공";
    if(input == "chinese") return "중국어문학전공";
    if(input == "math") return "수학과";
    if(input == "ai") return "AI학과";
    if(input == "chemEngineering") return "화학신소재공학과";
    if(input == "logistics") return "국제물류학과";
    if(input == "econ") return "경제학과";
    if(input == "physics") return "물리학과";
    if(input == "libInfoScience") return "문헌정보학과";
    if(input == "mediaComm") return "미디어커뮤니케이션학부";
    if(input == "sociology") return "사회학과";
    if(input == "socialWelfare") return "사회복지학과";
    if(input == "russian") return "러시아어문학전공";
    if(input == "french") return "프랑스어문학전공";
    if(input == "german") return "독일어문학전공";
    if(input == "philosophy") return "철학과";
    if(input == "history") return "역사학과";
    if(input == "publicService") return "공공인재학부";
    if(input == "civilEnvPlanEng") return "건설환경플랜트공학과";
    if(input == "urbanEngineering") return "도시시스템공학과";
    if(input == "architecture") return "건축학부";
    if(input == "appliedStat") return "응용통계학과";
    if(input == "med") return "의학과";
    if(input == "pharm") return "약학과";
    if(input == "adpr") return "광고홍보학과";
    if(input == "dorm") return "서울캠퍼스 기숙사";
    if(input == "upreJob") return "도시계획부동산학과 취업";
}

export default KRname;