import KRname from "./name_en2kr.js"

export function simpleUserInfo(user){
    let res = `${user.name}, ${user.email}, ${user.id}`;
    if(user.industSec == "true") res = res.concat(', ',KRname("industSec"));
    if(user.software == "true") res = res.concat(', ',KRname("software"));
    if(user.CAUnotice == "true") res = res.concat(', ',KRname("CAUnotice"));
    if(user.integEngineering == "true") res = res.concat(', ',KRname("integEngineering"));
    if(user.korean == "true") res = res.concat(', ',KRname("korean"));
    if(user.mechEngineering == "true") res = res.concat(', ',KRname("mechEngineering"));
    if(user.psychology == "true") res = res.concat(', ',KRname("psychology"));
    if(user.business == "true") res = res.concat(', ',KRname("business"));
    if(user.elecEngineering == "true") res = res.concat(', ',KRname("elecEngineering"));
    if(user.english == "true") res = res.concat(', ',KRname("english"));
    if(user.enerEngineering == "true") res = res.concat(', ',KRname("enerEngineering"));
    if(user.urbanPlanRealEstate == "true") res = res.concat(', ',KRname("urbanPlanRealEstate"));
    if(user.nursing == "true") res = res.concat(', ',KRname("nursing"));
    if(user.politics == "true") res = res.concat(', ',KRname("politics"));
    if(user.physicalEd == "true") res = res.concat(', ',KRname("physicalEd"));
    if(user.education == "true") res = res.concat(', ',KRname("education"));
    if(user.earlyChildhoodEd == "true") res = res.concat(', ',KRname("earlyChildhoodEd"));
    if(user.englishEd == "true") res = res.concat(', ',KRname("englishEd"));
    if(user.chem == "true") res = res.concat(', ',KRname("chem"));
    if(user.lifeScience == "true") res = res.concat(', ',KRname("lifeScience"));
    if(user.japanese == "true") res = res.concat(', ',KRname("japanese"));
    if(user.chinese == "true") res = res.concat(', ',KRname("chinese"));
    if(user.math == "true") res = res.concat(', ',KRname("math"));
    if(user.ai == "true") res = res.concat(', ',KRname("ai"));
    if(user.chemEngineering == "true") res = res.concat(', ',KRname("chemEngineering"));
    if(user.logistics == "true") res = res.concat(', ',KRname("logistics"));
    if(user.econ == "true") res = res.concat(', ',KRname("econ"));
    if(user.physics == "true") res = res.concat(', ',KRname("physics"));
    if(user.libInfoScience == "true") res = res.concat(', ',KRname("libInfoScience"));
    if(user.mediaComm == "true") res = res.concat(', ',KRname("mediaComm"));
    if(user.sociology == "true") res = res.concat(', ',KRname("sociology"));
    if(user.socialWelfare == "true") res = res.concat(', ',KRname("socialWelfare"));
    if(user.russian == "true") res = res.concat(', ',KRname("russian"));
    if(user.french == "true") res = res.concat(', ',KRname("french"));
    if(user.german == "true") res = res.concat(', ',KRname("german"));
    if(user.philosophy == "true") res = res.concat(', ',KRname("philosophy"));
    if(user.history == "true") res = res.concat(', ',KRname("history"));
    if(user.publicService == "true") res = res.concat(', ',KRname("publicService"));
    if(user.civilEnvPlanEng == "true") res = res.concat(', ',KRname("civilEnvPlanEng"));
    if(user.urbanEngineering == "true") res = res.concat(', ',KRname("urbanEngineering"));
    if(user.architecture == "true") res = res.concat(', ',KRname("architecture"));
    if(user.appliedStat == "true") res = res.concat(', ',KRname("appliedStat"));
    if(user.med == "true") res = res.concat(', ',KRname("med"));
    if(user.pharm == "true") res = res.concat(', ',KRname("pharm"));
    if(user.ADPR == "true") res = res.concat(', ',KRname("ADPR"));
    return res;
}
